#!/bin/bash

# Edit the variable below first to match your system:
# (in most circumstances, you probably don't have to change it at all)

grub_cfg_path="/boot/grub/grub.cfg" # The path where the generated GRUB configuration file is stored. Default is "/boot/grub/grub.cfg"

# Then place this file in /usr/sbin/
# sudo cp -v ./update-grub /usr/sbin/update-grub
# sudo chmod +x /usr/sbin/update-grub
# and then run
# sudo update-grub

# Sources:
# https://wiki.archlinux.org/title/GRUB#Generate_the_main_configuration_file


# Check if we're running as root:
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

# Next, update GRUB configuration:
read -p "Update GRUB configuration at $grub_cfg_path [y/N]? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    grub-mkconfig -o $grub_cfg_path "$@" && echo "Done."
else
    echo "Skipped."
fi